cSharpCourse/AspNetMVC/MVCStock/MVCStock/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCStock.Models.Entity;
namespace MVCStock.Controllers
{
    public class MusteriController : Controller
    {
        // GET: Musteri
        MvcDbStockEntities db = new MvcDbStockEntities();
        public ActionResult Index()
        {
            var musteriler = db.TBLMUSTERİLER.ToList();
            return View(musteriler);
        }
        [HttpGet]
        public ActionResult YeniMusteri()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniMusteri(TBLMUSTERİLER p1)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            db.TBLMUSTERİLER.Add(p1);
            db.SaveChanges();
            return View();
        }
        public ActionResult Sil(int id)
        {
            var musteri = db.TBLMUSTERİLER.Find(id);
            db.TBLMUSTERİLER.Remove(musteri);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Guncelle(int id) 
        {
            var musteriGuncelle = db.TBLMUSTERİLER.Find(id);
            return View(musteriGuncelle);
        }
        public ActionResult MusteriGuncelle(TBLMUSTERİLER p1)
        {
            var musteriGetir = db.TBLMUSTERİLER.Find(p1.MusteriId);
            musteriGetir.MusteriAd = p1.MusteriAd;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

cSharpCourse/AspNetMVC/MVCStock/MVCStock/Views/Musteri/Guncelle.cshtml
@model MVCStock.Models.Entity.TBLMUSTERİLER
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("MusteriGuncelle", "Musteri", FormMethod.Post))
{
   <div class="form-group">
       @Html.LabelFor(m => m.MusteriId);
       @Html.TextBoxFor(m => m.MusteriId, new {@class="form-control"})
       <br />
       @Html.LabelFor(m => m.MusteriAd);
       @Html.TextBoxFor(m => m.MusteriAd, new { @class = "form-control" })
       <br />
       @Html.LabelFor(m => m.MusteriSoyad);
       @Html.TextBoxFor(m => m.MusteriSoyad, new { @class = "form-control" })


       <br />
       <div>
           <button class="btn btn-warning">
               Müşteri Güncelle
           </button>
       </div>
   </div>
}

cSharpCourse/AspNetMVC/MVCStock/MVCStock/Views/Musteri/Index.cshtml
@using MVCStock.Models.Entity;
@model List<TBLMUSTERİLER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Müşeti Id</th>
        <th>Müşeti Ad</th>
        <th>Müşeti Soyad</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

    <tbody>
        @foreach (var musteriler in Model)
        {
            <tr>
                <th>@musteriler.MusteriId</th>
                <td>@musteriler.MusteriAd</td>
                <td>@musteriler.MusteriSoyad</td>
                <td><a href="/Musteri/Sil/@musteriler.MusteriId" class="btn btn-danger">SİL</a> </td>
                <td><a href="/Musteri/Guncelle/@musteriler.MusteriId" class="btn btn-success ">GÜNCELLE</a> </td>
            </tr>
        }
    </tbody>
</table>

<a href="/Musteri/YeniMusteri" class="btn btn-primary">Yeni Müşteri Ekle</a>

cSharpCourse/AspNetMVC/MVCStock/MVCStock/Views/Musteri/YeniMusteri.cshtml
@model MVCStock.Models.Entity.TBLMUSTERİLER
@{
    ViewBag.Title = "YeniMusteri";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    @*
        <div>
            <label>Müşteri Adı</label>
            <input type="text" class="form-control" name="MusteriAd" />
        </div>
    *@

    <div>
        <label>Müşteri Adı</label>
        @Html.TextBoxFor(m=>m.MusteriAd, new {@class= "form-control"})
        @Html.ValidationMessageFor(m=> m.MusteriAd, "", new {@style="color:red"})
    </div>
    <div>
        <label>Müşteri Soyadı</label>
        <input type="text" class="form-control" name="MusteriSoyad" />
    </div>

    <div style="margin-top:15px">
        <button class="btn btn-info">Müşteri Ekle</button>
    </div>
</form>