cSharpCourse/AspNetMVC/MVCStock/MVCStock/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCStock.Models.Entity;

namespace MVCStock.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun

        MvcDbStockEntities db = new MvcDbStockEntities();
        public ActionResult Index()
        {
            var urunler = db.TBLURUNLER.ToList();
            return View(urunler);
        }
        [HttpGet]
        public ActionResult YeniUrun()
        {
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList() 
                                             select new SelectListItem
                                             {
                                                 Text = i.KategoryAd, // text ile kategri adını alıp değer olarak o kategori adına karşılık gelen kategori ıd yi almayı sağlıyoruz.
                                                 Value = i.KategoryId.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View();
        }
        [HttpPost]
        public ActionResult YeniUrun(TBLURUNLER p1)
        {

            var ktg = db.TBLKATEGORILER.Where(m => m.KategoryId == p1.TBLKATEGORILER.KategoryId).FirstOrDefault();
            p1.TBLKATEGORILER = ktg;
            db.TBLURUNLER.Add(p1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Sil(int id)
        {
            var urun = db.TBLURUNLER.Find(id);
            db.TBLURUNLER.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Guncelle(int id)
        {
            var urunGuncelle = db.TBLURUNLER.Find(id);
            List<SelectListItem> degerler = (from i in db.TBLKATEGORILER.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = i.KategoryAd, // text ile kategri adını alıp değer olarak o kategori adına karşılık gelen kategori ıd yi almayı sağlıyoruz.
                                                 Value = i.KategoryId.ToString()
                                             }).ToList();
            ViewBag.dgr = degerler;
            return View(urunGuncelle);
        }
        public ActionResult UrunGuncelle(TBLURUNLER p1)
        {
            var urunGuncel = db.TBLURUNLER.Find(p1.UrunId);
            urunGuncel.UrunAd = p1.UrunAd;
            urunGuncel.Marka= p1.Marka;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

cSharpCourse/AspNetMVC/MVCStock/MVCStock/Views/Urun/Guncelle.cshtml
@model MVCStock.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@using (Html.BeginForm("UrunGuncelle","Urun",FormMethod.Post))
            {
                <div class="form-control">
                    @Html.LabelFor(m => m.UrunId)
                    @Html.TextBoxFor(m => m.UrunId, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.UrunAd)
                    @Html.TextBoxFor(m => m.UrunAd, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.Marka)
                    @Html.TextBoxFor(m => m.Marka, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.UrunKategory)
                    @Html.DropDownListFor(m => m.TBLKATEGORILER.KategoryId, (List<SelectListItem>)ViewBag.dgr, new { @class = "form-control"})
                    
                    @* @Html.TextBoxFor(m => m.UrunKategory, new { @class = "form-control" })*@
                    <br />
                    @Html.LabelFor(m => m.Fiyat)
                    @Html.TextBoxFor(m => m.Fiyat, new { @class = "form-control" })
                    <br />
                    @Html.LabelFor(m => m.Stok)
                    @Html.TextBoxFor(m => m.Stok, new { @class = "form-control" })
                    <br />

                    <div>
                        <button class="btn btn-warning">Ürün Güncelle</button>
                    </div>
                </div>
            }

cSharpCourse/AspNetMVC/MVCStock/MVCStock/Views/Urun/Index.cshtml
@using MVCStock.Models.Entity;;
@model List<TBLURUNLER>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Ürün Id</th>
        <th>Ürün Ad</th>
        <th>Marka</th>
        <th>Ürün Kategori</th>
        <th>Fiyat</th>
        <th>Stok</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>

    <tbody>
        @foreach (var urun in Model)
        {
            <tr>
                <td>@urun.UrunId</td>
                <td>@urun.UrunAd</td>
                <td>@urun.Marka</td>
                <td>@urun.UrunKategory</td>
                <td>@urun.Fiyat</td>
                <td>@urun.Stok</td>
                <td><a href="/Urun/Sil/@urun.UrunId" class="btn btn-danger">SİL</a> </td>
                <td><a href="/Urun/Guncelle/@urun.UrunId" class="btn btn-success ">GÜNCELLE</a> </td>
            </tr>
        }
    </tbody>

</table>
<a href="/Urun/YeniUrun" class="btn btn-primary">Yeni Ürün Ekle</a>

cSharpCourse/AspNetMVC/MVCStock/MVCStock/Views/Urun/YeniUrun.cshtml
@model MVCStock.Models.Entity.TBLURUNLER
@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    
    <div>
        <label>Ürün Adı</label>
        <input type="text" class="form-control" name="UrunAd" />
    </div>
    <div>
        <label>Marka</label>
        <input type="text" class="form-control" name="Marka" />
        <div>
            <label>Ürün Kategori</label>
           @Html.DropDownListFor(m=>m.TBLKATEGORILER.KategoryId,(List<SelectListItem>)ViewBag.dgr, new {@class="form-control"})
        </div>
    </div>
    <div>
        <label>Fiyat</label>
        <input type="text" class="form-control" name="Fiyat" />
        <div>
            <label>Stok</label>
            <input type="text" class="form-control" name="Stok" />
        </div>
    </div>

    <div style="margin-top:15px">
        <button class="btn btn-info">Ürün Ekle</button>
    </div>
</form>