cSharpCourse/AspNetMVC/MVCStock/MVCStock/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCStock.Models.Entity;

namespace MVCStock.Controllers
{
    public class KategoriController : Controller
    {
        // GET: Kategori

        MvcDbStockEntities db = new MvcDbStockEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLKATEGORILER.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult YeniKategori()
        {
            return View();
        }

        [HttpPost] // httpPost un kullanılmsı yeni kategori ekleme işleminde yanlızca herhangi bir değer döndürme durumunda ekleme işlemi yapar. aski durumda boş değer göndermez. Boş değer gönderme durumuda httpGet metodu çalışacak ve sayfaya null bir veri gönderilmeyecek
        public ActionResult YeniKategori(TBLKATEGORILER p1)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniKategori");
            }
            db.TBLKATEGORILER.Add(p1);
            db.SaveChanges();
            return View();
        }
        public ActionResult Sil(int id)
        {
            var ketgori = db.TBLKATEGORILER.Find(id);
            db.TBLKATEGORILER.Remove(ketgori);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Guncelle(int id)
        {
            var ktgr = db.TBLKATEGORILER.Find(id);
            return View(ktgr);
        }
        public ActionResult KategoriGuncelle(TBLKATEGORILER p1)
        {
            var ktgrGuncelle = db.TBLKATEGORILER.Find(p1.KategoryId);
            ktgrGuncelle.KategoryAd = p1.KategoryAd;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

cSharpCourse/AspNetMVC/MVCStock/MVCStock/Views/Kategori/Guncelle.cshtml
@model MVCStock.Models.Entity.TBLKATEGORILER
@{
    ViewBag.Title = "Guncelle";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@using (Html.BeginForm("KategoriGuncelle", "Kategori", FormMethod.Post))
{
                <div class="form-group">
                    @Html.LabelFor(m => m.KategoryId),
                    @Html.TextBoxFor(m => m.KategoryId, new {@class = "form-control"})
                    <br />

                    @Html.LabelFor(m => m.KategoryAd);
                    @Html.TextBoxFor(m => m.KategoryAd, new {@class = "form-control"})
                </div>
                <div>
                    <button class="btn btn-warning">Kategori Güncelle</button>
                </div>
}

cSharpCourse/AspNetMVC/MVCStock/MVCStock/Views/Kategori/Index.cshtml
@using MVCStock.Models.Entity;
@model List<TBLKATEGORILER>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<table class="table table-bordered">
    <tr>
        <th>Kategori ID</th>
        <th>Kategori ADI</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    <tbody>
        @foreach (var ktgr in Model)
        {
            <tr>
                <th>@ktgr.KategoryId</th>
                <td>@ktgr.KategoryAd</td>
                <td><a href="/Kategori/Sil/@ktgr.KategoryId" class="btn btn-danger">SİL</a> </td>
                <td><a href="/Kategori/Guncelle/@ktgr.KategoryId" class="btn btn-success ">GÜNCELLE</a> </td>
            </tr>

        }
    </tbody>
</table>

<a href="/Kategori/YeniKategori" class="btn btn-primary">Yeni Kategori Ekle</a>

cSharpCourse/AspNetMVC/MVCStock/MVCStock/Views/Kategori/YeniKategori.cshtml
@model MVCStock.Models.Entity.TBLKATEGORILER
@{
    ViewBag.Title = "YeniKategori";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<form class="form-group" method="post">
    @*
           <div>
            <label>Kategori Adı</label>
            <input  type="text" class="form-control" name="KategoryAd"/>
        </div>
    *@
    <div>
        <label>Kategori Adı</label>
        @Html.TextBoxFor(m=> m.KategoryAd, new {@class = "form-control"})
        @Html.ValidationMessageFor(m=>m.KategoryAd,"",new {@style="color:red"})
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Kategori Ekle</button>
    </div>
</form>